"""empty message

Revision ID: 47be2b1ce23f
Revises: 4d54aa9e2fc5
Create Date: 2022-04-18 09:51:54.655029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47be2b1ce23f'
down_revision = '4d54aa9e2fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('valor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos', 'valor')
    # ### end Alembic commands ###
