"""empty message

Revision ID: 4d54aa9e2fc5
Revises: 
Create Date: 2022-04-10 15:31:56.608437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d54aa9e2fc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf_cnpj', sa.String(), nullable=True),
    sa.Column('tipo_pessoa', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corretores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf_cnpj', sa.String(), nullable=True),
    sa.Column('tipo_pessoa', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proprietarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf_cnpj', sa.String(), nullable=True),
    sa.Column('tipo_pessoa', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('tipo_imovel', sa.String(), nullable=True),
    sa.Column('descricao_imovel', sa.String(), nullable=True),
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_proprietario'], ['proprietarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio_contrato', sa.String(), nullable=True),
    sa.Column('termino_contrato', sa.String(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_corretor', sa.Integer(), nullable=False),
    sa.Column('id_imovel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_corretor'], ['corretores.id'], ),
    sa.ForeignKeyConstraint(['id_imovel'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contratos')
    op.drop_table('imoveis')
    op.drop_table('proprietarios')
    op.drop_table('corretores')
    op.drop_table('clientes')
    # ### end Alembic commands ###
