"""empty message

Revision ID: 5523e6aa0ffe
Revises: 9b2dcb00c366
Create Date: 2022-04-25 19:33:46.117983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5523e6aa0ffe'
down_revision = '9b2dcb00c366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contratos', 'inicio_contrato',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('contratos', 'termino_contrato',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contratos', 'termino_contrato',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('contratos', 'inicio_contrato',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
