"""empty message

Revision ID: 9b2dcb00c366
Revises: be463a79429b
Create Date: 2022-04-25 19:30:04.674724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2dcb00c366'
down_revision = 'be463a79429b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos', sa.Column('inicio_contrato', sa.Date(), nullable=True))
    op.add_column('contratos', sa.Column('termino_contrato', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos', 'termino_contrato')
    op.drop_column('contratos', 'inicio_contrato')
    # ### end Alembic commands ###
