"""empty message

Revision ID: fbf2a234bb79
Revises: 569c69e4d07b
Create Date: 2022-04-25 19:19:09.022699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf2a234bb79'
down_revision = '569c69e4d07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contratos', 'id_cliente',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contratos', 'id_corretor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contratos', 'id_imovel',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contratos', 'id_imovel',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contratos', 'id_corretor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contratos', 'id_cliente',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
